Make scripts posix compliant

diff --git a/.local/bin/haste b/.local/bin/haste
--- a/.local/bin/haste
+++ b/.local/bin/haste
@@ -1,4 +1,5 @@
-#!/bin/bash
+#!/bin/sh
+set -e
 
 HASTE_MIRROR=${HASTE_MIRROR:-https://hb.vendicated.dev}
 
@@ -8,19 +9,19 @@ die() {
 }
 
 create_haste() {
-	res=$(curl -sS -f -XPOST $HASTE_MIRROR/documents -d "$1")
+	res=$(curl -sS -f -XPOST "$HASTE_MIRROR/documents" --data-binary "$1")
 	[ -z "$res" ] && die "Failed to post to $HASTE_MIRROR/documents. Consider changing mirror"
 	key=$(echo "$res" | jq -r .key 2> /dev/null)
-	[ -z $key ] && die "Failed to parse response"
-	echo $HASTE_MIRROR/$key | xclip -selection clipboard
+	[ -z "$key" ] && die "Failed to parse response"
+	echo "$HASTE_MIRROR/$key" | xclip -selection clipboard
 	notify-send "Haste" "Copied to clipboard"
 }
 
 if [ ! -t 0 ]; then
-	create_haste "$(cat)"
+	create_haste "@-"
 elif [ -n "$1" ]; then
 	text="$*"
-	[ -f "$1" ] && text=$(<"$1")
+	[ -f "$1" ] && text="@$1"
 	create_haste "$text"
 else
 	echo "Usage: $0 <text>"
diff --git a/.local/bin/owoscreenshot b/.local/bin/owoscreenshot
--- a/.local/bin/owoscreenshot
+++ b/.local/bin/owoscreenshot
@@ -1,12 +1,18 @@
 #!/bin/bash
+set -e
 
-if [ "$1" == "full" ]; then
+if [ "$1" = "full" ]; then
 	arg="screen"
 else
 	arg="gui"
 fi
 
 data="$(flameshot $arg --raw | base64)"
-[[ "$data" == $(base64 <<< "screenshot aborted") ]] && exit
+[ "$data" = "$(echo 'screenshot aborted' | base64)" ] && exit
 
-base64 -d <<< $data | owo -n _.png -t image/png - | xclip -selection clipboard && notify-send -i $HOME/.local/share/icons/owo.png OwO "Copied to clipboard"
+echo "$data" \
+	| base64 -d  \
+	| owo -n _.png -t image/png - \
+	| xclip -selection clipboard
+
+notify-send -i "$HOME/.local/share/icons/owo.png" OwO "Copied to clipboard"
